version: '2.3'
services:
  app:

    # Standard node image
    # https://github.com/nodejs/docker-node
    build:
      context: app

    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - "3000"

    # https://docs.npmjs.com/cli/start
    # Add tini init for signal handling
    #
    # Runs `server.js`
    init: True
    command: npm run dev
    environment:
      - DEBUG=gh-app-sand:*
  lt:
    build:
      context: localtunnel

    init: True
    command: --print-requests --subdomain asford-gh-app-sand --port 3000 --local-host app
    depends_on:
      - app
