version: '2.3'
services:
  app:
    # Add tini init for signal handling
    init: True

    # Standard node image
    # https://github.com/nodejs/docker-node
    image: "node:8"
    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - "3000"

    # Runs `server.js`
    # https://docs.npmjs.com/cli/start
    command: "npm start"
  lt:
    init: True

    build:
      context: localtunnel

    command: --print-requests --subdomain asford-gh-app-sand --port 3000 --local-host app
    depends_on:
      - app
