version: '2.3'
services:

  app:
    build:
      context: .
      dockerfile: app/Dockerfile

    ports:
      - "8080:8080"

    # https://docs.npmjs.com/cli/start
    # Add tini init for signal handling
    init: True
    command: python -m aiohttp.web -H 0.0.0.0 -P 8080 gh_app_sand.main:init

  lt:
    build:
      context: localtunnel

    init: True
    command: --print-requests --subdomain asford-gh-app-sand --port 8080 --local-host app
    depends_on:
      - app
