version: '2.3'
services:

  app:
    build:
      context: .
      dockerfile: app/Dockerfile

    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./:/app

    # https://docs.npmjs.com/cli/start
    # Add tini init for signal handling
    init: True
    command: adev runserver -p 8080 -v gh_app_sand

  lt:
    build:
      context: localtunnel

    init: True
    command: --print-requests --subdomain asford-gh-app-sand --port 8080 --local-host app
    depends_on:
      - app
