name: gh-app-sand
dependencies:
  - python=3.6
  - ipython
  - pytest
  - pip:
    - attrs
    - cattrs
    - aiohttp
    - aiorun
    - frozendict
    - click
    - pytest-watch
    - pytest-aiohttp
    - pytest-asyncio
    - giturlparse
    - decorator
